kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: env01-connector-client-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: netapp-trident-brz-retain
  volumeMode: Filesystem